---
title: "**Egalitarians' Honour Code**"
date: "13th Dec 2020"
output:
  beamer_presentation:
    theme: "Madrid"
    colortheme: "default"
    fonttheme: "default"
---
## Honour Code

1. Egalitarians is a leaderless, voluntary, and not-for-profit group deeply committed to the principle of equality. Thus, every member, irrespective of their age, social status and duration of associationship with the group, has equal right, responsibility, power, and privilege.

## Honour Code

2. Every member is an Egalitarian. Instead of using prefixes like Mr./Miss. EG (Egalitaraian) will be used as a honorific prefix for every member, irrespective of their gender-identity/sexual orientation and seniority.

## Honour Code

3. Egalitarians does not endorse any political party or organisations that are direclty related to a political party.

## Honour Code

4. Egaliarians will not participate in any protest for any cause unless and until all the constituitional means of redressals are exhausted. However, Egalitarians do not bar any of it's member from joining any protest in her/their/his own personal capacity.

## Honour Code

5. Any major decision conerning the group activity will be put to vote (either through voice-vote or electronic-vote) and the majority decision shall be accepted by the group. Any member of the group shall move any motion for voting the *Home rule* comittee will put the motion to vote.

## Honour Code

6. Any amendments to the *Egalitarians' Vision and Objectives* can only be passed with two-third majority.

## Honour Code

7. Egalitarians shall assemble (virtual or otherwise) once-in-every-month discussing workprogress and future strategy.

8. All activity and financial statements (donations, expenditure and balance) of Egalitarians shall be disclosed voluntarily through website and monthly newsletters.

## Honour Code

9. Egalitarians monthly newsletter carrying its activites and curated news articles shall be published (electronically or otherwise) every month on a predecided date.

10. Any member of the group found to be practising caste in any manner will cease to remain in the group.

## 

Why Telegram channel?

## 

mass mail at - egalitarians@googlegroups.com
